
#include <stdint.h>

#define GAMEBOYSTARTUP_BITS_PER_SAMPLE 16
#define GAMEBOYSTARTUP_SAMPLE_RATE 32000
#define GAMEBOYSTARTUP_SAMPLES 27014

extern const int16_t gameBoyStartup[GAMEBOYSTARTUP_SAMPLES];
